version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: webscraper
      POSTGRES_PASSWORD: webscraper
      POSTGRES_DB: webscraper
      PGDATA: webscraper/postgres/data
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - 5432:5432