# Generated by Django 4.2.1 on 2024-01-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldcars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_vin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
