# Generated by Django 4.2.1 on 2024-01-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldcars', '0002_alter_car_car_number_alter_car_car_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
